-- MySQL Script generated by MySQL Workbench
-- Wed May  6 14:09:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Team` (
  `id_team` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_team`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Match` (
  `id_match` INT NOT NULL AUTO_INCREMENT,
  `match_date` DATETIME NOT NULL,
  `home_team_id` INT NOT NULL,
  `away_team_id` INT NOT NULL,
  PRIMARY KEY (`id_match`),
  INDEX `fk_Match_Team1_idx` (`home_team_id` ASC) VISIBLE,
  INDEX `fk_Match_Team2_idx` (`away_team_id` ASC) VISIBLE,
  CONSTRAINT `fk_Match_Team1`
    FOREIGN KEY (`home_team_id`)
    REFERENCES `mydb`.`Team` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Team2`
    FOREIGN KEY (`away_team_id`)
    REFERENCES `mydb`.`Team` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `id_ticket` INT NOT NULL AUTO_INCREMENT,
  `seat` VARCHAR(100) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `id_customer` INT NOT NULL,
  `id_match` INT NOT NULL,
  PRIMARY KEY (`id_ticket`),
  INDEX `fk_Ticket_Customer1_idx` (`id_customer` ASC) VISIBLE,
  INDEX `fk_Ticket_Match1_idx` (`id_match` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Customer1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `mydb`.`Customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Match1`
    FOREIGN KEY (`id_match`)
    REFERENCES `mydb`.`Match` (`id_match`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
